[package]
name = "skrifheim-storage"
description = "Storage metadata and validation primitives for skrifheim."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
skrifheim-core = { version = "0.16.0", path = "../skrifheim-core" }
skrifheim-crypto = { version = "0.16.0", path = "../skrifheim-crypto" }

[lints]
workspace = true
