[package]
name = "skrifheim"
description = "Main crate and CLI for skrifheim."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
skrifheim-core = { version = "0.18.1", path = "../skrifheim-core" }
skrifheim-fact = { version = "0.18.1", path = "../skrifheim-fact" }
skrifheim-world = { version = "0.18.1", path = "../skrifheim-world" }
skrifheim-policy = { version = "0.18.1", path = "../skrifheim-policy" }
skrifheim-crypto = { version = "0.18.1", path = "../skrifheim-crypto" }
skrifheim-audit = { version = "0.18.1", path = "../skrifheim-audit" }
skrifheim-storage = { version = "0.18.1", path = "../skrifheim-storage" }
skrifheim-query = { version = "0.18.1", path = "../skrifheim-query" }

[lints]
workspace = true
