[package]
name = "skrifheim-crypto"
description = "Crypto-agile envelope types for skrifheim."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
skrifheim-core = { version = "0.15.0", path = "../skrifheim-core" }
sanitization = { version = "1.1.0", default-features = false, features = ["alloc"] }

[lints]
workspace = true
